### ISSUE TITLE
Minimizing the window causes a `panic!`

### ISSUE THREAD

**Issue by SpamSPez** [tonogram/nanolab-gui#10]
When pressing the window minimize button the program will crash. 

thread 'main' panicked at 'attempt to subtract with overflow', src\main.rs:**314:35**
Basically since window_size.height is assigned 0 it errors when subtracting:
**.size([500.0, (window_size.height - 28) as f32], Condition::Always)**

**Comment by tonogram** [comment]
Fixed with #40
