### ISSUE TITLE
Pick A Lab Window

### ISSUE THREAD

**Issue by SpamSPez** [tonogram/nanolab-gui#15]
Add a window before the current GUI that prompts user to select lab(s).
![image](https://user-images.githubusercontent.com/48837447/159489062-59baa852-eed0-4e8b-9775-7e8b01f0300a.png)

**Comment by tonogram** [comment]
I think, if anything, we mostly need better documentation. Child-friendly tutorials, manuals, stuff like that. We shouldn't need to redesign our UI or design an alternative UI just for something so niche.
